export default [
  {
    id: 'the-central-park',
    name: 'Manly Sea Eagles Fund',
    image: 'https://c2.staticflickr.com/4/3697/9003602547_c74a2b7146_b.jpg',
    LGA: 'Manly (A)',
    progress: 50,
    goal: 10000,
    pledge: 5000,
    day: 35,
    coordinates: { lat: -33.812749, lng: 150.996459 },
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  },
  {
    id: 'strathfield-train-station',
    name: 'Poop Free Strathfield',
    image: 'https://static.pexels.com/photos/164308/pexels-photo-164308.jpeg',
    LGA: 'Strathfield (A)',
    progress: 500,
    goal: 800,
    pledge: 650,
    day: 24,
    coordinates: { lat: -33.871672, lng: 151.09428560000003 },
    description:
      "Outside of Strathfield station, we need to clear the area of birds and their droppings. This is the first thing us Strathfield-ese folks see when we come out of the train station and likewise with everyone else who visits Strathfield. Let's keep Strathfield beautiful by cleaning it up which we will do as a community and we will also use $800 to install reflectors around to deflect the birds so that they don't mess it up afterwards ",
  },
  {
    id: 'parramatta-benches',
    name: 'Benches in Parramatta',
    image: 'https://static.pexels.com/photos/95684/pexels-photo-95684.jpeg',
    LGA: 'Parramatta (C)',
    progress: 4050,
    goal: 6000,
    pledge: 5500,
    day: 154,
    coordinates: { lat: -33.8174945, lng: 151.0013298 },
    description:
      "Who doesn't love a good stroll around the lovely City of Parramatta? Especially the elderly, unfortunately there are not enough places for them to rest along the long roads between Parramatta Park, Westfields and Eat Street (Church Street). We plan to install more benches so that they are able to go out for walks more while resting safely and bettering their physical activity and mental health. The money for this campaign will go towards 50 benches all up in this area",
  },
  {
    id: 'the-enhaced-security-infrastructure',
    name: 'The enchanced security infrastructure',
    image: 'https://s3-ap-southeast-2.amazonaws.com/webifycentral/images/proj2.png',
    LGA: 'Parramatta (C)',
    progress: 10,
    goal: 100000,
    pledge: 10000,
    day: 250,
    coordinates: { lat: -30.444, lng: 156.024869 },
    description:
      'Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras puru odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Doneclacinia congue felis in faucibus.',
  },
  {
    id: 'the-townhall-library',
    name: 'The Town hall library',
    LGA: 'Parramatta (C)',
    image: 'https://s3-ap-southeast-2.amazonaws.com/webifycentral/images/proj3.jpg',
    progress: 15,
    goal: 200000,
    pledge: 25000,
    day: 55,
    coordinates: { lat: -33.821876, lng: 150.997489 },
    description:
      'Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras puru odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Doneclacinia congue felis in faucibus.',
  },
  {
    id: 'great-butterfly-park',
    LGA: 'Parramatta (C)',
    name: 'Great butterfly park',
    image: 'https://s3-ap-southeast-2.amazonaws.com/webifycentral/images/proj4.png',
    progress: 75,
    goal: 17234,
    pledge: 10000,
    day: 10,
    coordinates: { lat: -33.811893, lng: 151.024869 },
    description:
      'Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras puru odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Doneclacinia congue felis in faucibus.',
  },
];
